---
title: "Projet M2 2022-23"
subtitle: 'Modèles pour la régression'
author: "Mettre vos noms ICI"
output: 
  pdf_document: 
    keep_tex: no
fontsize: 12pt    
header-includes:
- \usepackage{pifont}
- \usepackage{manfnt}
- \usepackage{mdframed}
- \usepackage{systeme}
- \usepackage{txfonts}
- \newcommand{\cH}{\mathcal{H}}

params:
  path_data_folder: "../data/"
  path_R_folder: "../R/"
---

# Parameters
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', warning=FALSE,message=FALSE)

source(paste(params$path_R_folder,"libraries.R", sep=''))
source(paste(params$path_R_folder,"functions.R", sep=''))
source(paste(params$path_R_folder,"preprocessing.R", sep=''))
set.seed(2022)

init_train <- read.csv2(paste(params$path_data_folder, "train.csv",sep=''),
                   header=TRUE, 
                   sep=",")
init_test <- read.csv2(paste(params$path_data_folder, "test.csv", sep=''), 
                  header=TRUE, 
                  sep=",")

target <- 'SalePrice'

num_vars <- c(
  'SalePrice',
  'Size.sqf.',
  'YearBuilt',
  'YrSold',
  'MonthSold',
  'N_FacilitiesNearBy.PublicOffice.',
  'N_FacilitiesNearBy.Hospital.',
  'N_FacilitiesNearBy.Dpartmentstore.',
  'N_FacilitiesNearBy.Mall.',
  'N_FacilitiesNearBy.ETC.',
  'N_FacilitiesNearBy.Park.',
  'N_SchoolNearBy.Elementary.',
  'N_SchoolNearBy.Middle.',
  'N_SchoolNearBy.High.',
  'N_SchoolNearBy.University.',
  'N_FacilitiesInApt',
  'N_FacilitiesNearBy.Total.',
  'N_SchoolNearBy.Total.',
  'N_Parkinglot.Ground.',
  'N_Parkinglot.Basement.',
  'N_APT',
  'N_manager',
  'N_elevators',
  'Floor'
)

chr_vars <- c(
  'HallwayType',
  'HeatingType',
  'AptManageType',
  'TimeToBusStop',
  'TimeToSubway',
  'SubwayStation'
)
train <- set_numerics(init_train, num_vars)
```


# No modification

### lm
```{r}
train <- init_train
test <- init_test

model = lm(SalePrice ~., data = train)
model %>% summary

model_pred <- model %>%
  predict(newdata=test)

RMSE(model_pred, test$SalePrice)
```

### stepAIC
```{r}
model0 <- lm(SalePrice~1, train)
model <- stepAIC(model0, direction="forward", trace=TRUE)

model_pred <- predict(model, newdata=test)

RMSE(model_pred, test$SalePrice)
```
```{r}

```


# Only numeric
```{r}
train_quant <- train %>%
  select_if(is.numeric)

model <- lm(SalePrice ~ ., train_quant)
model %>% summary

model_pred <- model %>%
  predict(newdata=test)

RMSE(model_pred, test$SalePrice)
```
# Num as Quant
```{r}
train <- set_numerics(train, num_vars)

model.train <- train %>% select_if(is.numeric)

model <- lm(SalePrice~., model.train)
model %>% summary

test <- set_numerics(test, num_vars)
model_pred <- predict(model, newdata = test)

RMSE(model_pred, test$SalePrice)
```
```{r}
train
```

# With preproc - all
```{r}
train <- train %>% preprocessing()
train <- train %>% factorize()

model <- lm(SalePrice ~., train)
a <- model %>% summary()

test <- test %>% set_numerics(num_vars)
test <- test %>% preprocessing()
test <- test %>% factorize

model_pred <- predict(model, newdata=test)

RMSE(model_pred, test$SalePrice)
```

```{r}
train <- init_train
train <- train %>% set_numerics(num_vars)
train <- train %>% preprocessing
train <- train %>% factorize

sel_vars <- train %>% colnames %>% sample(20, replace=F)

formula <- paste(target, '~', sep = " ")
for(i in seq_along(sel_vars)){
  ifelse(i==1,
         formula <- paste(formula, sel_vars[i], sep = ' '),
         formula <- paste(formula, sel_vars[i], sep = ' + '))
}; rm(i)
formula <- as.formula(formula)
formula

model0 <- lm(formula, train)
model0 %>% summary

stepAIC(model0, direction='both', trace=T)
```

# One var
```{r}
set.seed(2022)

train <- init_train
train <- train %>% set_numerics(num_vars)
train <- train %>% preprocessing
train <- train %>% factorize

test <- init_test
test <- test %>% set_numerics(num_vars)
test <- test %>% preprocessing
test <- test %>% factorize

vars <- colnames(train)

dfRes <- data.frame()
for(var in vars){
  formula <- paste(target, '~', sep = " ")
  formula <- paste(formula, var, sep='+')
  
  model <- lm(formula, train)
  model_pred <- predict(model, newdata=test)
  
  rmse <- RMSE(model_pred, test$SalePrice)
  lRes <- list(target=target, var=var, RMSE=rmse)
  
  dfRes <- rbind(dfRes, lRes)
}

sorted_res <- dfRes[order(dfRes[,'RMSE'], decreasing = FALSE),]
write.csv(sorted_res, '../output/lm_1var.csv', row.names=F)

sorted_res
```


# Best 2-3 combi
```{r}
require(gtools, install.packages('gtools'))
combi2 <- combinations(n =length(colnames(train)), r = 2, colnames(train))
combi2 <- cbind(combi2, rep(NA, times = nrow(combi2)))
combi3 <- combinations(n =length(colnames(train)), r = 3, colnames(train))
combi_all <- rbind(combi2, combi3)

get_formula <- function(target, combirow){
  formula <- paste(target, '~', sep = " ")
  for(i in seq_along(combirow)){
    ifelse(i==1,
           formula <- paste(formula, combirow[i], sep = ' '),
           ifelse(is.na(combirow[i]), 
                  formula,
                  formula <- paste(formula, combirow[i], sep = ' + ')
                  )
           )
  }
  formula <- as.formula(formula)
}
```
```{r}
train <- init_train
train <- train %>% set_numerics(num_vars)
train <- train %>% preprocessing
train <- train %>% factorize

test <- init_test
test <- test %>% set_numerics(num_vars)
test <- test %>% preprocessing()
test <- test %>% factorize

lRes <- apply(combi_all, 1, function(combirow){
  model <- lm(get_formula(target, combirow), train)
  model_pred <- predict(model, newdata=test)
  output_RMSE <- list(RMSE = RMSE(model_pred, test$SalePrice) )
  output_vars <- list(
    Target = target, 
    Var1 = combirow[1], 
    Var2 = combirow[2], 
    Var3 = combirow[3]
    )
  return(c(output_vars, output_RMSE))
})

dfRes <- data.frame()
for(elem in lRes) dfRes <- rbind(dfRes, elem)

sorted_res <- dfRes[order(dfRes[,'RMSE'], decreasing = FALSE),]
write.csv(sorted_res, '../output/lm_2-3vars.csv', row.names=F)

sorted_res
```

# N_facilities_Nearby

### Modèle global
```{r}
set.seed(2022)

train <- init_train
train <- train %>% set_numerics(num_vars)
train <- train %>% preprocess.N_Facilities_Nearby(strat='corr', drop=T)

test <- init_test
test <- test %>% set_numerics(num_vars)
test <- test %>% preprocess.N_Facilities_Nearby(strat='corr', drop=T)

model = lm(SalePrice ~., data = train)
model %>% summary

model_pred <- model %>%
  predict(newdata=test)

RMSE(model_pred, test$SalePrice)
```
### Comparaison
```{r}
set.seed(2022)

train <- init_train
train <- train %>% set_numerics(num_vars)
train <- train %>% 
  dplyr::select(-N_FacilitiesNearBy.Total.) %>%
  dplyr::select(c(SalePrice, starts_with('N_Facilities_NearBy')))
train %>% str

test <- init_test
test <- test %>% set_numerics(num_vars)
test <- test %>% 
  dplyr::select(-c('N_FacilitiesNearBy.Total.')) %>%
  dplyr::select(c(SalePrice, starts_with('N_Facilities_NearBy')))
test %>% str

model <- lm(SalePrice~., train)
model %>% summary

model_pred <- predict(model, newdata=test)
RMSE(model_pred, test$SalePrice)
```

# Macro
```{r}
set.seed(2022)

train <- init_train
train <- train %>% set_numerics(num_vars)

Q1 <- quantile(train$SalePrice, probs = 0.25)
Q3 <- quantile(train$SalePrice, probs = 0.75)
IQR <- Q3-Q1

train_IQ <- filter(train, SalePrice > Q1 - 1.5 * IQR & SalePrice < Q3 + 1.5 * IQR)

train <- train_IQ

test <- init_test
test <- test %>% set_numerics(num_vars)

model <- lm(SalePrice ~ Size.sqf. + YearBuilt + YrSold + MonthSold + SubwayStation, train)
model %>% summary()

model_pred <- predict(model, newdata=test)
RMSE(model_pred, test$SalePrice)
```

```{r}
create_new_var <- function(data, var1, var2, contingency_table){
  # Initialiser une liste vide pour stocker les modalités de la nouvelle variable
  new_levels <- c()

  # Parcourir les lignes du tableau de contingence pour créer les modalités de la nouvelle variable
  for (i in 1:nrow(contingency_table)) {
    for(j in 1:ncol(contingency_table)){
      # Si le croisement a des occurences, créer une modalité correspondante
      if (contingency_table[i,j] > 0) {
        new_levels <- c(new_levels, 
                        paste(rownames(contingency_table)[i],
                              colnames(contingency_table)[j], 
                              sep = "_"))
      }else{
        # Sinon, attribuer la modalité 'Autres'
        new_levels <- c(new_levels, "Autres")
      }
    }
  }
  
  # Initialiser une liste vide pour stocker les modalités de la nouvelle variable pour chaque observation
  new_var <- c()
  
  # Parcourir les observations du dataframe pour attribuer la modalité correspondante à chaque observation
  for (i in 1:nrow(data)) {
    # Récupérer les modalités des deux variables d'entrée pour l'observation i
    var1_modality <- data[i, var1]
    var2_modality <- data[i, var2]
    # Récupérer l'index de la modalité correspondante dans la liste new_levels
    index <- which(new_levels == paste(var1_modality, var2_modality, sep = "_"))
    if (length(index) == 0) {
      index <- which(new_levels == "Autres")
    }
    # Ajouter la modalité correspondante à la liste new_var
    new_var <- c(new_var, new_levels[index])
  }
  
  # Ajouter la nouvelle variable au dataframe
  name_new_var = sprintf('%s_%s', var1, var2)
  data[, name_new_var] <- new_var
  
  return(data)
}
```

