---
title: "Ridge"
author: "Alexandre Robin"
date: "`r Sys.Date()`"
output: html_document

params:
  path_data_folder: "../data/"
  path_R_folder: "../R/"
---

# Parameters
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', warning=FALSE,message=FALSE)

source(paste(params$path_R_folder,"libraries.R", sep=''))
source(paste(params$path_R_folder,"functions.R", sep=''))
source(paste(params$path_R_folder,"preprocessing.R", sep=''))

init_train <- read.csv2(paste(params$path_data_folder, "train.csv",sep=''),
                   header=TRUE, 
                   sep=",")
init_test <- read.csv2(paste(params$path_data_folder, "test.csv", sep=''), 
                  header=TRUE, 
                  sep=",")
target <- 'SalePrice'

num_vars <- c(
  'SalePrice',
  'Size.sqf.',
  'YearBuilt',
  'YrSold',
  'MonthSold',
  'N_FacilitiesNearBy.PublicOffice.',
  'N_FacilitiesNearBy.Hospital.',
  'N_FacilitiesNearBy.Dpartmentstore.',
  'N_FacilitiesNearBy.Mall.',
  'N_FacilitiesNearBy.ETC.',
  'N_FacilitiesNearBy.Park.',
  'N_SchoolNearBy.Elementary.',
  'N_SchoolNearBy.Middle.',
  'N_SchoolNearBy.High.',
  'N_SchoolNearBy.University.',
  'N_FacilitiesInApt',
  'N_FacilitiesNearBy.Total.',
  'N_SchoolNearBy.Total.',
  'N_Parkinglot.Ground.',
  'N_Parkinglot.Basement.',
  'N_APT',
  'N_manager',
  'N_elevators',
  'Floor'
)

chr_vars <- c(
  'HallwayType',
  'HeatingType',
  'AptManageType',
  'TimeToBusStop',
  'TimeToSubway',
  'SubwayStation'
)
train <- init_train %>% set_numerics(num_vars)
train <- init_train %>% mutate_if(is.character, as.factor)
```

# Engineering
```{r}
engineering = function(data){
  cat_vars = c('N_Parkinglot.Ground.', 
               'N_Parkinglot.Basement.',
               'N_APT', 'N_manager', 'N_elevators',
               'N_FacilitiesNearBy.PublicOffice.',
               'N_FacilitiesNearBy.Dpartmentstore.',
               'N_FacilitiesNearBy.Mall.',
               'N_FacilitiesNearBy.ETC.', 
               'N_FacilitiesNearBy.Park.',
               'N_SchoolNearBy.Elementary.', 
               'N_SchoolNearBy.Middle.',
               'N_SchoolNearBy.High.', 
               'N_SchoolNearBy.University.',
               'N_FacilitiesInApt', 
               'N_FacilitiesNearBy.Total.',
               'N_SchoolNearBy.Total.', 
               'HallwayType', 'HeatingType', 'AptManageType',
               'TimeToBusStop', 'TimeToSubway', 'SubwayStation',
               'N_FacilitiesNearBy.Hospital.',
               'MonthSold', 'YrSold', "YearBuilt")
  int_vars = c("SalePrice", "Size.sqf.",'Floor')
  data = data %>% mutate_at(vars(matches(int_vars)), as.integer)
  data = data %>% mutate_at(vars(matches(cat_vars)), as.factor)
  return(data)
}

train_engineered <- init_train %>% engineering
test_engineered <- init_test %>% engineering
```

# Preprocessing
```{r}
train <- train_engineered
test <- test_engineered

Q1 <- quantile(train$SalePrice, probs = 0.25)
Q3 <- quantile(train$SalePrice, probs = 0.75)
IQR <- Q3-Q1

train <- train %>% 
  filter(SalePrice > Q1 - 1.5 * IQR & SalePrice < Q3 + 1.5 * IQR)

preproc <- caret::preProcess(train)
training <- predict(preproc, train)
test <- predict(preproc, test)
```

# Ridge
```{r}
alpha_grid <- seq(1e-10, 1e-6, length = 20)

# Configurer la recherche en grille
alpha_grid <- expand.grid(alpha=alpha_grid, 
                          lambda=0)

alpha_final <- caret::train(sqrt(SalePrice) ~ 
                              Size.sqf.+YrSold+
                              MonthSold+N_Parkinglot.Ground.+
                              Floor+TimeToBusStop,
                            data = train,
                            method = "glmnet",
                            tuneGrid = alpha_grid,
                            trControl = trainControl(method="cv", 
                                                     number=5),
                            family = 'gaussian')
alpha_final_pred <- predict(alpha_final, newdata=test)
RMSE(alpha_final_pred**2, test$SalePrice)
```

